DirectoryPath: "public"
CacheExpires: 168h # 1 week
CheckExternal: true
CheckInternalHash: true
EnforceHTTPS: true
IgnoreAltEmpty: true # Ignore alt=""
IgnoreAltMissing: false
IgnoreCanonicalBrokenLinks: true
IgnoreDirectoryMissingTrailingSlash: true
IgnoreEmptyHref: true # Ignore href=""
IgnoreInternalEmptyHash: true # Ignore href="#"
IgnoreURLs:
- ".*index.xml" # Ignore index.xml files
- ".*example.com.*"
- ".*contoso.com.*"
- ".*xmlsoap.org.*"
- ".*graph.microsoft.com.*"