baseURL = 'https://chriscodes.net/'
languageCode = 'en-us'
title = 'chrisxfires blog'
theme = "hugo-blog-awesome"
defaultContentLanguage = "en-gb"
# disableKinds = ["section"]

# set markup.highlight.noClasses=false to enable code highlight
[markup]
  [markup.highlight]
    noClasses = false
  [markup.goldmark.renderer]
    unsafe = true

[menu]
  [[menu.main]] 
    # The page reference (pageRef) is useful for menu highlighting
    # When pageRef is set, setting `url` is optional; it will be used as a fallback if the page is not found.
    pageRef = "/"
    name = "home"
    url = "/"
    weight = 10
  [[menu.main]]
    pageRef = "posts"
    name = "posts"
    url = "/posts/"
    weight = 20
  [[menu.main]]
    pageRef = "notes"
    name = "notes"
    url = "/notes/"
    weight = 30
  [[menu.main]]
    pageRef = "readings"
    name = "readings"
    url = "/reading-recaps/"
    weight = 30
  [[menu.main]]
    pageRef = "about"
    name = "about"
    url = "/about/"
    weight = 90

[params]
  sitename = "chricodes.net"
  defaultColor = "dark" # set default color mode: dark or light or auto
  description = "chrisxfire blog"
  mainSections = ['posts']
  toc = false # set to false to disable table of contents 'globally'
  goToTop = true # set to false to disable 'go to top' button
  showReadingTime = true # whether to show reading time on lists and posts

[params.author]
  avatar = "chrisxfire.jpg" # put the file in assets folder; also ensure that image has same height and width
  # Note: image is not rendered if the resource(avatar image) is not found. No error is displayed.
  intro = "rants, raves, and ruminations"
  name = "chrisxfire"
  description = "a blog about software engineering with .NET (with occasional digressions)"

# Allow to override webmanifest options
[params.webmanifest]
  name = "chriscodes.net" # will use "params.sitename" or "title" by default
  short_name = "chriscodes.net" # same as name
  start_url = "/" # will use homepage url by default
  theme_color = "#434648" # default is "#434648" (base color of text). Also will override html `<meta name="theme-color" />`
  background_color = "#fff" # by default depend on "params.defaultColor" for "light" or "auto" will be set to "#fff" for dark will be "#131418" (color of dark mode background)
  display = "standalone"

# Allow to override `browserconfig.xml` params (configuration for windows embeded browsers)
[params.browserconfig]
  TileColor = "#2d89ef" # default windows 10 blue tile color

[[params.socialIcons]]
name = "github"
url = "https://github.com/chrisxfire"

[[params.socialIcons]]
name = "keybase"
url = "https://keybase.io/chrisxfire"

[[params.socialIcons]]
name = "Rss"
url = "index.xml"

[params.giscus]
repo = "chrisxfire/chrisxfire.github.io"
repoID = "R_kgDOJL96QQ"
category = "Comments"
categoryID = "DIC_kwDOJL96Qc4CVk8Y"
mapping = "pathname"
strict = "0"
reactionsEnabled = "1"
emitMetadata = "0"
inputPosition = "top"
theme = "preferred_color_scheme"
lang = "en"
loading = "lazy"