baseURL = 'https://chriscodes.net/'
languageCode = 'en-us'
title = 'chrisxfires blog'
theme = "hugo-blog-awesome"

# set markup.highlight.noClasses=false to enable code highlight
[markup]
  [markup.highlight]
    noClasses = false
  [markup.goldmark.renderer]
    unsafe = true

[menu]
  [[menu.main]] 
    # The page reference (pageRef) is useful for menu highlighting
    # When pageRef is set, setting `url` is optional; it will be used as a fallback if the page is not found.
    pageRef="/"
    name = 'Home'
    url = '/'
    weight = 10
  [[menu.main]]
    pageRef="posts"
    name = 'Posts'
    url = '/posts/'
    weight = 20
  [[menu.main]]
    pageRef="about"
    name = 'About'
    url = '/about/'
    weight = 30

[params]
  sitename = "params sitename"
  defaultColor = "dark" # set default color mode: dark or light
  description = "params description"

[params.author]
  avatar = "chrisxfire.jpg" # put the file in assets folder; also ensure that image has same height and width
  # Note: image is not rendered if the resource(avatar image) is not found. No error is displayed.
  intro = "rants, raves, and ruminations"
  name = "chrisxfire"
  description = "a blog about software engineering with .NET (with occasional digressions)"

[[params.socialIcons]]
name = "github"
url = "https://github.com/chrisxfire"

[[params.socialIcons]]
name = "keybase"
url = "https://keybase.io/chrisxfire"

[[params.socialIcons]]
name = "Rss"
url = "index.xml"

[[params.giscus]]
repo = "chrisxfire/chrisxfire.github.io"
repoID = "R_kgDOJL96QQ"
category = "Comments"
categoryID = "DIC_kwDOJL96Qc4CVk8Y"
mapping = "pathname"
reactionsEnabled = "1"
emitMetadata = "0"
inputPosition = "top"
theme = "dark"
lang = "en"
loading = "lazy"